---
# tasks file for load_balancers
- name: Creating template
  template:
    src: ../files/load_balancer_config.j2
    dest: /etc/httpd/conf.d/lb.conf
    owner: bin
    group: wheel
    mode: 064

- name: restart apache
  service: name=httpd state=restarted