pipeline {
    agent { label "slave-1" }
    options { skipDefaultCheckout(true) }
    stages {
        stage('checking the Java version') {
            steps {
		echo "Running on slave-1 node.."
                sh 'java --version'
        
	    }
        }
    }
}
