---
# tasks file for roles/webservers
- name: Upload application file
  copy:                         # Copies the app file from local to remote servers
    src: ../files/index.php
    dest: "{{ path_to_app }}"
    mode: 0755

- name: Create a simple info page
  copy:
    dest: "{{ path_to_app }}/info.php"
    content: "<h1> Info about our webserver {{ ansible_hostname }} <h1>" (closing h1 is an error here.)
  ignore_errors: yes

- name: Get the OS type of the hosts
  shell: uname
  changed_when: false
  register: uname_output   # Registers the output of the uname command in uname_output variable

- name: print the uname output
  debug: msg="{{ uname_output.stdout }}"  # prints the stdout key value in the uname_output variable.

- yum:
    name: "*"
    state: latest
  when: uname_output.stdout == "Linux"
  changed_when: false

- name: configure php.ini file  # Configure the php.ini file to accept the short open tag
  lineinfile:
    path: /etc/php.ini
    regexp: ^short_open_tag     # Allows the user to write the php files with short open tags
    line: 'short_open_tag=On'
  notify: restart apache